export const menuItems = [
  {
    id: "1",
    name: "Grilled Chicken",
    price: 2420.99,
    image: "https://picsum.photos/seed/food1/300/200",
    category: "Main Course",
  },
  {
    id: "2",
    name: "Beef Steak",
    price: 3420.99,
    image: "https://picsum.photos/seed/food2/300/200",
    category: "Main Course",
    discount: 10,
  },
  {
    id: "3",
    name: "Fish Curry",
    price: 1820.99,
    image: "https://picsum.photos/seed/food3/300/200",
    category: "Main Course",
  },
  {
    id: "4",
    name: "Vegetable Pasta",
    price: 1620.99,
    image: "https://picsum.photos/seed/food4/300/200",
    category: "Pasta",
    discount: 15,
  },
  {
    id: "5",
    name: "Chicken Burger",
    price: 1220.99,
    image: "https://picsum.photos/seed/food5/300/200",
    category: "Fast Food",
  },
  {
    id: "6",
    name: "Caesar Salad",
    price: 820.99,
    image: "https://picsum.photos/seed/food6/300/200",
    category: "Salads",
    discount: 5,
  },
  {
    id: "7",
    name: "Chocolate Cake",
    price: 620.99,
    image: "https://picsum.photos/seed/food7/300/200",
    category: "Desserts",
  },
  {
    id: "8",
    name: "Ice Cream",
    price: 420.99,
    image: "https://picsum.photos/seed/food8/300/200",
    category: "Desserts",
    discount: 20,
  },
  {
    id: "9",
    name: "Fruit Juice",
    price: 320.99,
    image: "https://picsum.photos/seed/food9/300/200",
    category: "Beverages",
  },
  {
    id: "10",
    name: "Coffee",
    price: 220.99,
    image: "https://picsum.photos/seed/food10/300/200",
    category: "Beverages",
  },
];
